name: githubActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: ./install_criterion.sh
    - name: make
      run: build
    - name: make test
      run: build_test
